- PointHome/src/main/java/com/pointhome/www/mypage/controller/MypageController.java
- PointHome/src/main/webapp/WEB-INF/views/mypage/mypick.jsp
> 230523 유지수

- PointHome/src/main/webapp/WEB-INF/views/mypage/mypick.jsp
> 230523 유지수 mypage css 수정

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/service/face/FreeBoardService.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/java/com/pointhome/www/user/service/face/UserService.java
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
> 230523 kdh 게시판 충돌 해결 완료

- PointHome/src/main/webapp/WEB-INF/views/layout/footer.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/myprofile.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/view.jsp
> 230524 hsy header footer

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/dto/FreeBoardRecommend.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/face/FreeBoardService.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/list.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/recommend.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/header.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
> 230524 hsy freeboard 필터 빼고 완성

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/service/face/FreeBoardService.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/write.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
230504 곽도현 다중파일 업로드, 미리보기, 삭제 구현완료
> 230504 곽도현 다중파일 업로드, 미리보기, 삭제 구현완료

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
> 2023 05 24 jihoon park 진짜 최신

- PointHome/src/main/webapp/WEB-INF/views/freeboard/list.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/listFilter.jsp
> 230524 hsy filter 이제시작

- PointHome/src/main/java/com/pointhome/www/mypage/controller/MypageController.java
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/dto/Partner.java
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/user/service/face/UserService.java
- PointHome/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- PointHome/src/main/webapp/WEB-INF/views/mypage/myreview.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/userinfo.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/join.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/login.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/main.jsp
- PointHome/src/main/webapp/resources/mypage/userInfo.css
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230525 유지수 partner 만듬

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/service/face/FreeBoardService.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/list.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/listFilter.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/myprofile.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/serviceCenter.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/view.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
> 230526 hsy 필터

- PointHome/pom.xml
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/java/com/pointhome/www/user/kakao/controller/kakaoController.java
- PointHome/src/main/java/com/pointhome/www/user/service/impl/OAuthService.java
- PointHome/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- PointHome/src/main/webapp/WEB-INF/views/user/kakaologin.jsp
- PointHome/target/m2e-wtp/web-resources/META-INF/maven/com.pointhome/www/pom.xml
> 230506 유지수 카카오 로그인 구현중

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/service/face/FreeBoardService.java
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/updateComment.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
> 2023 05 26 댓글 수정 박지

- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/java/com/pointhome/www/user/dao/face/UserDao.java
- PointHome/src/main/java/com/pointhome/www/user/dao/mapper/UserDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/user/service/face/UserService.java
- PointHome/src/main/java/com/pointhome/www/user/service/impl/UserServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/join.jsp
- PointHome/src/main/webapp/WEB-INF/views/user/join.jsp
- PointHome/target/classes/com/pointhome/www/user/dao/mapper/UserDaoMapper.xml
230529 김해성 user 소셜로그인 insert 처리중
> 230529 김해성 user 소셜로그인 insert 처리중

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/dto/AdminNotice.java
- PointHome/src/main/java/com/pointhome/www/admin/dto/AdminNoticeFile.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/write.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/adminHeader.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230530 유지수 운영사 공지사항 List & 제휴사/사용자 필터, 글쓰기 구현완료
> 230530 유지수 운영사 공지사항 List & 제휴사/사용자 필터, 글쓰기 구현완료

- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230531 김해성 userController 오류 수정
> 230531 김해성 userController 오류 수정

- PointHome/src/main/java/com/pointhome/www/mypage/controller/MypageController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/layout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/typelist.jsp
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
This file contains the commit message for a merge commit.
> Inconsistent merge state: could not find file MERGE_MSG in .git folder.

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/prc/prc.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reservation.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reserveDateAjax.jsp
> 230602 - reservation edit

- PointHome/src/main/java/com/pointhome/www/main/controller/mainController.java
- PointHome/src/main/java/com/pointhome/www/main/dao/mapper/MainMapper.xml
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/views/main/reservation.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reserveDateAjax.jsp
- PointHome/target/classes/com/pointhome/www/main/dao/mapper/MainMapper.xml
> 230602 홍승연 결제 기능 수정

- PointHome/pom.xml
- PointHome/target/m2e-wtp/web-resources/META-INF/maven/com.pointhome/www/pom.xml
> 230605 김해성 pom.xml 정리

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/dto/AdminNotice.java
- PointHome/src/main/java/com/pointhome/www/admin/dto/AdminNoticeFile.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/sidebar.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/sidebarContainer.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/adminnoticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/partnernotice.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/user/adminnoticelist.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
사용자 - 제휴사,이용자 공지사항jsp (읽기전용페이지) 연동
> 230627 유지수 운영사 제휴사 공지사항 글쓰기 수정, 삭제 ,파일업로드

- PointHome/src/main/java/com/pointhome/www/main/controller/mainController.java
- PointHome/src/main/java/com/pointhome/www/main/dao/face/MainDao.java
- PointHome/src/main/java/com/pointhome/www/main/dao/mapper/MainMapper.xml
- PointHome/src/main/java/com/pointhome/www/main/dto/Reservation.java
- PointHome/src/main/java/com/pointhome/www/main/service/face/MainService.java
- PointHome/src/main/java/com/pointhome/www/main/service/impl/MainServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/layout/detailBanner.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/detail.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reservation.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reserveDateAjax.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/join.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/shopsetting.jsp
- PointHome/target/classes/com/pointhome/www/main/dao/mapper/MainMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230607 홍승연 예약 결제 완료

- PointHome/src/main/java/com/pointhome/www/freeboard/dao/face/FreeBoardDao.java
- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/service/impl/FreeBoardServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/main/dao/mapper/MainMapper.xml
- PointHome/src/main/java/com/pointhome/www/mypage/controller/MypageController.java
- PointHome/src/main/java/com/pointhome/www/mypage/dao/face/MypageDao.java
- PointHome/src/main/java/com/pointhome/www/mypage/dao/mapper/MypageMapper.xml
- PointHome/src/main/java/com/pointhome/www/mypage/dto/Alert.java
- PointHome/src/main/java/com/pointhome/www/mypage/service/face/MypageService.java
- PointHome/src/main/java/com/pointhome/www/mypage/service/impl/MypageServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/detail.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/alertList.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/myreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/mypage/view.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/target/classes/com/pointhome/www/main/dao/mapper/MainMapper.xml
- PointHome/target/classes/com/pointhome/www/mypage/dao/mapper/MypageMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
230608 곽도현 알림내역 구현, 게시판 글 작성 수정
> 230608 곽도현 알림내역 구현, 게시판 글 작성 수정

- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
> 230608 홍승연 깃 이상한거 수정

- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/layout/footer.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/user/join.jsp
- PointHome/src/main/webapp/WEB-INF/views/user/login.jsp
- PointHome/src/main/webapp/resources/common/css/font.css
- PointHome/src/main/webapp/resources/join/user/js/Email.js
230608 김해성 웹폰트변경 session.invalidate()위치 변경
> 230608 김해성 웹폰트변경 session.invalidate()위치 변경

- PointHome/src/main/java/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/dto/PartnerVideo.java
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/list.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/viewVideo.jsp
- PointHome/target/classes/com/pointhome/www/freeboard/dao/mapper/FreeBoardMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
2023 06 09 게시판 검색 닉네임 추가, 게시판 검색 엔터 구현, 제휴사 유투브 영상 삽입,url 변경,삭제 중복검사
> 2023 06 09 게시판 검색 닉네임 추가, 게시판 검색 엔터 구현, 제휴사 유투브 영상 삽입,url 변경,삭제 중복검사

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/admin/partnermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userboardpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/sidebar.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/update.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
> 230609 운영사 제휴사 상세보기 페이징, 필터링, 검색 기능 구현

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/partnermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usercmtpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/updateComment.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230611 지수 사용자 게시글, 댓글 상세보기 삭제,수정 페이징 필터링 서치 구현
> 230611 지수 사용자 게시글, 댓글 상세보기 삭제,수정 페이징 필터링 서치 구현

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partupdatereserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partupdatereserveajax.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/header.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230613 지수 제휴사 - 운영사 예약조회, 수정 구현중
> 230613 지수 제휴사 - 운영사 예약조회, 수정 구현중

- PointHome/src/main/java/com/pointhome/www/main/controller/mainController.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/layout/myprofile.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/detail.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/detail_old.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/reserveDateAjax.jsp
> 230613 홍승연 유저 제휴사 상세페이지 완료

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/admin/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnervideo.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/sidebar.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230614 지수 운영사페이지 제휴사 홍보영상 삭제, 메인페이지 수정
> 230614 지수 운영사페이지 제휴사 홍보영상 삭제, 메인페이지 수정

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/webapp/WEB-INF/views/freeboard/list.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/updateComment.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/write.jsp
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
2023 06 15 게시판 작성 레이어창 띄우기 css 수정, 상세보기 css 수정 본문 오류 수정 , 리스트 베너 추가,
> 2023 06 15 게시판 작성 레이어창 띄우기 css 수정, 상세보기 css 수정 본문 오류 수정 , 리스트 베너 추가,

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/payment.jsp
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
203615 지수 운영사 결제내역 조회 구현 , 운영사 페이지 메인 수정
> 203615 지수 운영사 결제내역 조회 구현 , 운영사 페이지 메인 수정

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/admin/login.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/main2.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/adminHeader.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/sidebar.jsp
> 230616 지수 운영사페이지 css 수정

- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/webapp/WEB-INF/views/partner/list.jsp
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230616 홍승연 /partner/list

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/login.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/main2.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnervideo.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partupdatereserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partupdatereserveajax.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/payment.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/review.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userboardpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usercmtpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usermanage.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
> 230617 지수 운영사 css 수정

- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230618 홍승연 파트너리스트 페이징 수정

- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
230618 홍승연 /freeboard/list 로그인 안하면 나는 오류 수정
> 230618 홍승연 /freeboard/list 로그인 안하면 나는 오류 수정

- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/freeboard/controller/FreeBoardController.java
- PointHome/src/main/webapp/WEB-INF/views/admin/login.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnervideo.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/payment.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/review.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userboardpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/usercmtpost.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userdetail.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userreserve.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/view.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
> 230608 지수 admin css 수정

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/admin/error.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
> 230618 wltn admin css update

- PointHome/src/main/webapp/WEB-INF/views/admin/error.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/partnerupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/userupdate.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
> 230619 지수 admin 수정

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/layout/adminLayout/sidebar.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/partnernotice.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
230619 지수 운영사 수정, 제휴사 공지사항 삭제버튼 생성
> 230619 지수 운영사 수정, 제휴사 공지사항 삭제버튼 생성

- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
- PointHome/src/main/webapp/WEB-INF/views/freeboard/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/main/detail.jsp
> 230619 홍승연

- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/views/chat/chatting.jsp
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230619 - chat session edit

- PointHome/src/main/webapp/WEB-INF/spring/root-context.xml
- PointHome/src/main/webapp/WEB-INF/views/partner/main.jsp
> 230619 홍승연 파트너 메인 고침

- PointHome/src/main/java/com/pointhome/www/user/controller/userController.java
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/user/join.jsp
- PointHome/src/main/webapp/resources/join/user/js/Email.js
- PointHome/src/main/webapp/resources/join/user/js/Kakao_postAPI.js
> 230619 김해성 회원가입 유효성검사 버그 수정

- PointHome/src/main/java/com/pointhome/www/admin/controller/AdminController.java
- PointHome/src/main/java/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/src/main/java/com/pointhome/www/admin/dao/face/AdminDao.java
- PointHome/src/main/java/com/pointhome/www/admin/service/face/AdminService.java
- PointHome/src/main/java/com/pointhome/www/admin/service/impl/AdminServiceImpl.java
- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/dto/PartnerNotice.java
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/admin/noticelist.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/update.jsp
- PointHome/src/main/webapp/WEB-INF/views/admin/writenotice.jsp
- PointHome/src/main/webapp/WEB-INF/views/layout/partnerLayout/header.jsp
- PointHome/src/main/webapp/WEB-INF/views/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/partnernotice.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/view.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/writenotice.jsp
- PointHome/target/classes/com/pointhome/www/admin/dao/Mapper/AdminMapper.xml
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230619 어드민 수정 지수

- PointHome/src/main/java/com/pointhome/www/partner/controller/PartnerController.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/face/PartnerDao.java
- PointHome/src/main/java/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
- PointHome/src/main/java/com/pointhome/www/partner/service/face/PartnerService.java
- PointHome/src/main/java/com/pointhome/www/partner/service/impl/PartnerServiceImpl.java
- PointHome/src/main/webapp/WEB-INF/views/main/detail.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/main.jsp
- PointHome/src/main/webapp/WEB-INF/views/partner/partnernotice.jsp
- PointHome/target/classes/com/pointhome/www/partner/dao/mapper/PartnerDaoMapper.xml
> 230619 홍승연 마지막
